-- Display all available tables in the Sakila database.

USE sakila;
SHOW tables;

-- Write SQL queries to perform the following tasks using the Sakila database:

-- List the number of films per category.
SELECT fc.category_id, COUNT(f.film_id) as number_of_film FROM film AS f
LEFT JOIN film_category AS fc
ON f.film_id = fc.film_id
GROUP BY fc.category_id;
-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id,
ci.city,
co.country
FROM store as s
LEFT JOIN address as ad
ON s.address_id = ad.address_id
LEFT JOIN city as ci
ON ad.city_id = ci.city_id
LEFT JOIN country as co
ON ci.country_id = co.country_id;
-- Calculate the total revenue generated by each store in dollars.
SELECT s.store_id,
SUM(p.amount) AS revenue_in_dollars
FROM store as s
LEFT JOIN staff as st
on s.store_id = st.store_id
LEFT JOIN payment as p
on st.staff_id = p.staff_id
GROUP BY s.store_id;
-- Determine the average running time of films for each category.
SELECT fc.category_id, 
c.name,
round(AVG(f.length),0) as average_running_min FROM film AS f
LEFT JOIN film_category AS fc
ON f.film_id = fc.film_id
LEFT JOIN category as c
ON fc.category_id = c.category_id
GROUP BY fc.category_id, c.name;
